[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
gnosis_mainnet = "https://rpc.gnosischain.com"
gnosis_testnet = "https://rpc.chaidochain.net"

[etherscan]
gnosis_mainnet = { url = "https://api.gnosisscan.io/api", key = "${GNOSISSCAN_KEY}", chain = 100 }
